import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Email sender app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full h-screen bg-black bg-image">{children}</body>
    </html>
  );
}
